services:
  - type: web
    name: amazon-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true
